FROM java

#COPY target/docker-java-helloworld-0.0.1-SNAPSHOT.jar /usr/docker-java-helloworld-0.0.1-SNAPSHOT.jar

ADD docker-java-helloworld-0.0.1-SNAPSHOT.jar docker-java-helloworld-0.0.1-SNAPSHOT.jar

CMD java -cp docker-java-helloworld-0.0.1-SNAPSHOT.jar main.Helloworld